package ec.edu.unl.ws.sgaws.wsacademica.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

//import org.jboss.seam.annotations.security.RoleCheck;

/**
 * This class was generated by Apache CXF 2.2.5
 * Fri Apr 26 10:59:26 ECT 2013
 * Generated source version: 2.2.5
 * 
 */
 
@WebService(targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/", name = "SGAWebServicesAcademica_PortType")
@XmlSeeAlso({ec.edu.unl.ws.sgaws.wsacademica.soap.types.ObjectFactory.class})
public interface SGAWebServicesAcademicaPortType {

    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
    @RequestWrapper(localName = "sgaws_unidades_docentes_paralelo", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsUnidadesDocentesParalelo")
    @ResponseWrapper(localName = "sgaws_unidades_docentes_paraleloResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsUnidadesDocentesParaleloResponse")
    @WebMethod(operationName = "sgaws_unidades_docentes_paralelo", action = "sgaws_unidades_docentes_paralelo")
    public java.lang.String sgawsUnidadesDocentesParalelo(
        @WebParam(name = "id_paralelo", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
        java.lang.String idParalelo
    );

    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
    @RequestWrapper(localName = "sgaws_estudiante_matriculas", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsEstudianteMatriculas")
    @ResponseWrapper(localName = "sgaws_estudiante_matriculasResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsEstudianteMatriculasResponse")
    @WebMethod(operationName = "sgaws_estudiante_matriculas", action = "sgaws_estudiante_matriculas")
    public java.lang.String sgawsEstudianteMatriculas(
        @WebParam(name = "id_carrera", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
        java.lang.String idCarrera,
        @WebParam(name = "cedula", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
        java.lang.String cedula
    );

    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
    @RequestWrapper(localName = "sgaws_info_matricula", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsInfoMatricula")
    @ResponseWrapper(localName = "sgaws_info_matriculaResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsInfoMatriculaResponse")
    @WebMethod(operationName = "sgaws_info_matricula", action = "sgaws_info_matricula")
    public java.lang.String sgawsInfoMatricula(
        @WebParam(name = "mid", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
        java.lang.String mid
    );

    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
    @RequestWrapper(localName = "sgaws_egresados", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsEgresados")
    @ResponseWrapper(localName = "sgaws_egresadosResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsEgresadosResponse")
    @WebMethod(operationName = "sgaws_egresados", action = "sgaws_egresados")
    public java.lang.String sgawsEgresados(
        @WebParam(name = "fecha", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
        java.lang.String fecha
    );

    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
    @RequestWrapper(localName = "sgaws_reporte_matricula", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsReporteMatricula")
    @ResponseWrapper(localName = "sgaws_reporte_matriculaResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsReporteMatriculaResponse")
    @WebMethod(operationName = "sgaws_reporte_matricula", action = "sgaws_reporte_matricula")
    public java.lang.String sgawsReporteMatricula(
        @WebParam(name = "id_oferta", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
        java.lang.String idOferta,
        @WebParam(name = "cedula", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
        java.lang.String cedula
    );

    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
    @RequestWrapper(localName = "sgaws_fechas_matriculaoa", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsFechasMatriculaoa")
    @ResponseWrapper(localName = "sgaws_fechas_matriculaoaResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsFechasMatriculaoaResponse")
    @WebMethod(operationName = "sgaws_fechas_matriculaoa", action = "sgaws_fechas_matriculaoa")
    public java.lang.String sgawsFechasMatriculaoa(
        @WebParam(name = "id_oferta", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
        java.lang.String idOferta
    );

    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
    @RequestWrapper(localName = "sgaws_periodos_lectivos", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsPeriodosLectivos")
    @ResponseWrapper(localName = "sgaws_periodos_lectivosResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsPeriodosLectivosResponse")
    @WebMethod(operationName = "sgaws_periodos_lectivos", action = "sgaws_periodos_lectivos")
    public java.lang.String sgawsPeriodosLectivos();

    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
    @RequestWrapper(localName = "sgaws_ofertas_academicas", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsOfertasAcademicas")
    @ResponseWrapper(localName = "sgaws_ofertas_academicasResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsOfertasAcademicasResponse")
    @WebMethod(operationName = "sgaws_ofertas_academicas", action = "sgaws_ofertas_academicas")
    public java.lang.String sgawsOfertasAcademicas(
        @WebParam(name = "id_periodo", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
        java.lang.String idPeriodo
    );

    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
    @RequestWrapper(localName = "sgaws_plan_estudio", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsPlanEstudio")
    @ResponseWrapper(localName = "sgaws_plan_estudioResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsPlanEstudioResponse")
    @WebMethod(operationName = "sgaws_plan_estudio", action = "sgaws_plan_estudio")
    public java.lang.String sgawsPlanEstudio(
        @WebParam(name = "id_paralelo", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
        java.lang.String idParalelo
    );

    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
    @RequestWrapper(localName = "sgaws_estadoestudiantes_paralelo", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsEstadoestudiantesParalelo")
    @ResponseWrapper(localName = "sgaws_estadoestudiantes_paraleloResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsEstadoestudiantesParaleloResponse")
    @WebMethod(operationName = "sgaws_estadoestudiantes_paralelo", action = "sgaws_estadoestudiantes_paralelo")
    public java.lang.String sgawsEstadoestudiantesParalelo(
        @WebParam(name = "id_paralelo", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
        java.lang.String idParalelo
    );

    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
    @RequestWrapper(localName = "sgaws_notas_estudiante", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsNotasEstudiante")
    @ResponseWrapper(localName = "sgaws_notas_estudianteResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsNotasEstudianteResponse")
    @WebMethod(operationName = "sgaws_notas_estudiante", action = "sgaws_notas_estudiante")
    public java.lang.String sgawsNotasEstudiante(
        @WebParam(name = "cedula", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
        java.lang.String cedula,
        @WebParam(name = "id_carrera", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
        java.lang.String idCarrera,
        @WebParam(name = "id_oferta", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
        java.lang.String idOferta
    );

    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
    @RequestWrapper(localName = "sgaws_carga_horaria_docente", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsCargaHorariaDocente")
    @ResponseWrapper(localName = "sgaws_carga_horaria_docenteResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsCargaHorariaDocenteResponse")
    @WebMethod(operationName = "sgaws_carga_horaria_docente", action = "sgaws_carga_horaria_docente")
    public java.lang.String sgawsCargaHorariaDocente(
        @WebParam(name = "id_oferta", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
        java.lang.String idOferta,
        @WebParam(name = "cedula", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
        java.lang.String cedula
    );

    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
    @RequestWrapper(localName = "sgaws_carreras_estudiante", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsCarrerasEstudiante")
    @ResponseWrapper(localName = "sgaws_carreras_estudianteResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types", className = "ec.edu.unl.ws.sgaws.wsacademica.soap.types.SgawsCarrerasEstudianteResponse")
    @WebMethod(operationName = "sgaws_carreras_estudiante", action = "sgaws_carreras_estudiante")
    public java.lang.String sgawsCarrerasEstudiante(
        @WebParam(name = "cedula", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/types")
        java.lang.String cedula
    );
}
