package ec.edu.unl.ws.sgaws.wsacademica.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * WSDL File for SGAWebServicesAcademica
 *
 * This class was generated by Apache CXF 2.6.3
 * 2013-10-22T10:37:40.939-05:00
 * Generated source version: 2.6.3
 * 
 */
@WebServiceClient(name = "SGAWebServicesAcademica", 
                  wsdlLocation = "file:/home/cesar/wsdls/academica.wsdl",
                  targetNamespace = "http://ws.unl.edu.ec/sgaws/wsacademica/soap/") 
public class SGAWebServicesAcademica extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.unl.edu.ec/sgaws/wsacademica/soap/", "SGAWebServicesAcademica");
    public final static QName SGAWebServicesAcademicaPortType = new QName("http://ws.unl.edu.ec/sgaws/wsacademica/soap/", "SGAWebServicesAcademica_PortType");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/cesar/wsdls/academica.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SGAWebServicesAcademica.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/cesar/wsdls/academica.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SGAWebServicesAcademica(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SGAWebServicesAcademica(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SGAWebServicesAcademica() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SGAWebServicesAcademica(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SGAWebServicesAcademica(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SGAWebServicesAcademica(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SGAWebServicesAcademicaPortType
     */
    @WebEndpoint(name = "SGAWebServicesAcademica_PortType")
    public SGAWebServicesAcademicaPortType getSGAWebServicesAcademicaPortType() {
        return super.getPort(SGAWebServicesAcademicaPortType, SGAWebServicesAcademicaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SGAWebServicesAcademicaPortType
     */
    @WebEndpoint(name = "SGAWebServicesAcademica_PortType")
    public SGAWebServicesAcademicaPortType getSGAWebServicesAcademicaPortType(WebServiceFeature... features) {
        return super.getPort(SGAWebServicesAcademicaPortType, SGAWebServicesAcademicaPortType.class, features);
    }

}
