package ec.edu.unl.ws.sgaws.wspersonal.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * WSDL File for SGAWebServicesPersonal
 *
 * This class was generated by Apache CXF 2.6.3
 * 2013-10-22T09:51:16.497-05:00
 * Generated source version: 2.6.3
 * 
 */
@WebServiceClient(name = "SGAWebServicesPersonal", 
                  wsdlLocation = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/api.wsdl",
                  targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/") 
public class SGAWebServicesPersonal extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.unl.edu.ec/sgaws/wspersonal/soap/", "SGAWebServicesPersonal");
    public final static QName SGAWebServicesPersonalPortType = new QName("http://ws.unl.edu.ec/sgaws/wspersonal/soap/", "SGAWebServicesPersonal_PortType");
    static {
        URL url = null;
        try {
            url = new URL("http://ws.unl.edu.ec/sgaws/wspersonal/soap/api.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SGAWebServicesPersonal.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/cesar/servidores/jboss-as-7.2.0.Alpha1-SNAPSHOT/wsdls/personal.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SGAWebServicesPersonal(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SGAWebServicesPersonal(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SGAWebServicesPersonal() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SGAWebServicesPersonal(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SGAWebServicesPersonal(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SGAWebServicesPersonal(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SGAWebServicesPersonalPortType
     */
    @WebEndpoint(name = "SGAWebServicesPersonal_PortType")
    public SGAWebServicesPersonalPortType getSGAWebServicesPersonalPortType() {
        return super.getPort(SGAWebServicesPersonalPortType, SGAWebServicesPersonalPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SGAWebServicesPersonalPortType
     */
    @WebEndpoint(name = "SGAWebServicesPersonal_PortType")
    public SGAWebServicesPersonalPortType getSGAWebServicesPersonalPortType(WebServiceFeature... features) {
        return super.getPort(SGAWebServicesPersonalPortType, SGAWebServicesPersonalPortType.class, features);
    }

}
