
package ec.edu.unl.ws.sgaws.wspersonal.soap;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.BindingType;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.soap.SOAPBinding;


/**
 * WSDL File for SGAWebServicesPersonal
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "SGAWebServicesPersonal", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/", wsdlLocation = "file:/home/cesar/servidores/jboss-as-7.2.0.Alpha1-SNAPSHOT/wsdls/api2.wsdl")
@BindingType("http://java.sun.com/xml/ns/jaxws/2003/05/soap/bindings/HTTP/")
public class SGAWebServicesPersonal
    extends Service
{

    private final static URL SGAWEBSERVICESPERSONAL_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ec.edu.unl.ws.sgaws.wspersonal.soap.SGAWebServicesPersonal.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ec.edu.unl.ws.sgaws.wspersonal.soap.SGAWebServicesPersonal.class.getResource(".");
            url = new URL(baseUrl, "/home/cesar/servidores/jboss-as-7.2.0.Alpha1-SNAPSHOT/wsdls/api2.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/cesar/wsdls/personal.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SGAWEBSERVICESPERSONAL_WSDL_LOCATION = url;
    }

    public SGAWebServicesPersonal(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SGAWebServicesPersonal() {
        super(SGAWEBSERVICESPERSONAL_WSDL_LOCATION, new QName("http://ws.unl.edu.ec/sgaws/wspersonal/soap/", "SGAWebServicesPersonal"));
    }

    /**
     * 
     * @return
     *     returns SGAWebServicesPersonalPortType
     */
    @WebEndpoint(name = "SGAWebServicesPersonal_PortType")
    public SGAWebServicesPersonalPortType getSGAWebServicesPersonalPortType() {
        return super.getPort(new QName("http://ws.unl.edu.ec/sgaws/wspersonal/soap/", "SGAWebServicesPersonal_PortType"), SGAWebServicesPersonalPortType.class);
    }

}
