package ec.edu.unl.ws.sgaws.wspersonal.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-10-22T09:51:16.440-05:00
 * Generated source version: 2.6.3
 * 
 */
@WebService(targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/", name = "SGAWebServicesPersonal_PortType")
@XmlSeeAlso({ec.edu.unl.ws.sgaws.wspersonal.soap.types.ObjectFactory.class})
public interface SGAWebServicesPersonalPortType {

    /**
     * Retorna los datos personales actualizados de todos los estudiantes desde la fecha fecha
     * 	Los datos que retorna son:
     * TODO: falta por hacer no se ha hecho nada
     * 	cedula, nombres, apellidos, fecha_nacimiento, telefono, celular, direccion_actual, pais_actual, ciudad_actual, email, genero
     * 		La salida de este metodo se encuentra formateada con JSON, por lo que para su utilizacion el resultado debe de ser decodificado con JSON
     * 	
     */
    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types")
    @RequestWrapper(localName = "sgaws_datos_personales", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types", className = "ec.edu.unl.ws.sgaws.wspersonal.soap.types.SgawsDatosPersonales")
    @WebMethod(operationName = "sgaws_datos_personales", action = "sgaws_datos_personales")
    @ResponseWrapper(localName = "sgaws_datos_personalesResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types", className = "ec.edu.unl.ws.sgaws.wspersonal.soap.types.SgawsDatosPersonalesResponse")
    public java.lang.String sgawsDatosPersonales(
        @WebParam(name = "fecha", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types")
        java.lang.String fecha
    );

    /**
     * Este metodo recibe como parametro de entrada la cedula de un docente.
     *    	Retorna los datos del docente  de acuerdo a la cedula ingresada.
     * 	Los datos que retorna son:
     * 	nombres, apellidos, cedula, titulo y catergoria laboral
     * 	La salida de este metodo se encuentra formateada con JSON, por lo que para su utilizacion el resultado debe de ser decodificado con JSON
     * 	
     */
    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types")
    @RequestWrapper(localName = "sgaws_datos_docente", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types", className = "ec.edu.unl.ws.sgaws.wspersonal.soap.types.SgawsDatosDocente")
    @WebMethod(operationName = "sgaws_datos_docente", action = "sgaws_datos_docente")
    @ResponseWrapper(localName = "sgaws_datos_docenteResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types", className = "ec.edu.unl.ws.sgaws.wspersonal.soap.types.SgawsDatosDocenteResponse")
    public java.lang.String sgawsDatosDocente(
        @WebParam(name = "cedula", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types")
        java.lang.String cedula
    );

    /**
     * Este metodo recibe como parametro de entrada la cedula de un usuario.
     *        Retorna los datos de un usuario diferenciando si es estudiante, docente o ambos
     * 	Los datos que retorna son:
     * 	tipos de usuario,nombres,apellidos y cedula de usuario
     * 	La salida de este metodo se encuentra formateada con JSON, por lo que para su utilizacion el resultado debe de ser decodificado con JSON
     *        
     */
    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types")
    @RequestWrapper(localName = "sgaws_datos_usuario", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types", className = "ec.edu.unl.ws.sgaws.wspersonal.soap.types.SgawsDatosUsuario")
    @WebMethod(operationName = "sgaws_datos_usuario", action = "sgaws_datos_usuario")
    @ResponseWrapper(localName = "sgaws_datos_usuarioResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types", className = "ec.edu.unl.ws.sgaws.wspersonal.soap.types.SgawsDatosUsuarioResponse")
    public java.lang.String sgawsDatosUsuario(
        @WebParam(name = "cedula", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types")
        java.lang.String cedula
    );

    /**
     * Este metodo recibe como parametro de entrada la cedula de un estudiante.
     *        Retorna los datos del estudiante de acuerdo a la cedula ingresada.
     * 	Los datos que retorna son:
     * 	cedula, nombres, apellidos, fecha_nacimiento, telefono, celular, direccion_actual, pais_actual, ciudad_actual, email, genero
     * 		La salida de este metodo se encuentra formateada con JSON, por lo que para su utilizacion el resultado debe de ser decodificado con JSON
     * 	
     */
    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types")
    @RequestWrapper(localName = "sgaws_datos_estudiante", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types", className = "ec.edu.unl.ws.sgaws.wspersonal.soap.types.SgawsDatosEstudiante")
    @WebMethod(operationName = "sgaws_datos_estudiante", action = "sgaws_datos_estudiante")
    @ResponseWrapper(localName = "sgaws_datos_estudianteResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types", className = "ec.edu.unl.ws.sgaws.wspersonal.soap.types.SgawsDatosEstudianteResponse")
    public java.lang.String sgawsDatosEstudiante(
        @WebParam(name = "cedula", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types")
        java.lang.String cedula
    );
}
