
package ec.edu.unl.ws.sgaws.wspersonal.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SGAWebServicesPersonal_PortType", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/")
public interface SGAWebServicesPersonalPortType {


    /**
     * 
     * 	Este metodo recibe como parametro de entrada la cedula de un docente.
     *     	Retorna los datos del docente  de acuerdo a la cedula ingresada.
     * 	Los datos que retorna son:
     * 	nombres, apellidos, cedula, titulo y catergoria laboral
     * 	La salida de este metodo se encuentra formateada con JSON, por lo que para su utilizacion el resultado debe de ser decodificado con JSON
     * 	
     * 
     * @param cedula
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "sgaws_datos_docente", action = "sgaws_datos_docente")
    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types")
    @RequestWrapper(localName = "sgaws_datos_docente", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types", className = "ec.edu.unl.ws.sgaws.wspersonal.soap.types.SgawsDatosDocente")
    @ResponseWrapper(localName = "sgaws_datos_docenteResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types", className = "ec.edu.unl.ws.sgaws.wspersonal.soap.types.SgawsDatosDocenteResponse")
    public String sgawsDatosDocente(
        @WebParam(name = "cedula", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types")
        String cedula);

    /**
     * 
     * 	Este metodo recibe como parametro de entrada la cedula de un estudiante.
     *         Retorna los datos del estudiante de acuerdo a la cedula ingresada.
     * 	Los datos que retorna son:
     * 	cedula, nombres, apellidos, fecha_nacimiento, telefono, celular, direccion_actual, pais_actual, ciudad_actual, email, genero
     * 		La salida de este metodo se encuentra formateada con JSON, por lo que para su utilizacion el resultado debe de ser decodificado con JSON
     * 	
     * 
     * @param cedula
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "sgaws_datos_estudiante", action = "sgaws_datos_estudiante")
    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types")
    @RequestWrapper(localName = "sgaws_datos_estudiante", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types", className = "ec.edu.unl.ws.sgaws.wspersonal.soap.types.SgawsDatosEstudiante")
    @ResponseWrapper(localName = "sgaws_datos_estudianteResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types", className = "ec.edu.unl.ws.sgaws.wspersonal.soap.types.SgawsDatosEstudianteResponse")
    public String sgawsDatosEstudiante(
        @WebParam(name = "cedula", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types")
        String cedula);

    /**
     * 
     *         Retorna los datos personales actualizados de todos los estudiantes desde la fecha fecha
     * 	Los datos que retorna son:
     *         TODO: falta por hacer no se ha hecho nada
     * 	cedula, nombres, apellidos, fecha_nacimiento, telefono, celular, direccion_actual, pais_actual, ciudad_actual, email, genero
     * 		La salida de este metodo se encuentra formateada con JSON, por lo que para su utilizacion el resultado debe de ser decodificado con JSON
     * 	
     * 
     * @param fecha
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "sgaws_datos_personales", action = "sgaws_datos_personales")
    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types")
    @RequestWrapper(localName = "sgaws_datos_personales", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types", className = "ec.edu.unl.ws.sgaws.wspersonal.soap.types.SgawsDatosPersonales")
    @ResponseWrapper(localName = "sgaws_datos_personalesResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types", className = "ec.edu.unl.ws.sgaws.wspersonal.soap.types.SgawsDatosPersonalesResponse")
    public String sgawsDatosPersonales(
        @WebParam(name = "fecha", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types")
        String fecha);

    /**
     * 
     * 	Este metodo recibe como parametro de entrada la cedula de un usuario.
     *         Retorna los datos de un usuario diferenciando si es estudiante, docente o ambos
     * 	Los datos que retorna son:
     * 	tipos de usuario,nombres,apellidos y cedula de usuario
     * 	La salida de este metodo se encuentra formateada con JSON, por lo que para su utilizacion el resultado debe de ser decodificado con JSON
     *         
     * 
     * @param cedula
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "sgaws_datos_usuario", action = "sgaws_datos_usuario")
    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types")
    @RequestWrapper(localName = "sgaws_datos_usuario", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types", className = "ec.edu.unl.ws.sgaws.wspersonal.soap.types.SgawsDatosUsuario")
    @ResponseWrapper(localName = "sgaws_datos_usuarioResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types", className = "ec.edu.unl.ws.sgaws.wspersonal.soap.types.SgawsDatosUsuarioResponse")
    public String sgawsDatosUsuario(
        @WebParam(name = "cedula", targetNamespace = "http://ws.unl.edu.ec/sgaws/wspersonal/soap/types")
        String cedula);

}
