package ec.edu.unl.ws.sgaws.wsvalidacion.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-10-22T10:20:24.171-05:00
 * Generated source version: 2.6.3
 * 
 */
@WebService(targetNamespace = "http://ws.unl.edu.ec/sgaws/wsvalidacion/soap/", name = "SGAWebServicesValidacion_PortType")
@XmlSeeAlso({ec.edu.unl.ws.sgaws.wsvalidacion.soap.types.ObjectFactory.class})
public interface SGAWebServicesValidacionPortType {

    /**
     * Este metodo recibe como parametros de entrada la cedula y la clave del docente.
     * 	Retorna true o false dependiendo de los si la informacion enviada pertenece a un docente.
     * 	
     */
    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsvalidacion/soap/types")
    @RequestWrapper(localName = "sgaws_validar_docente", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsvalidacion/soap/types", className = "ec.edu.unl.ws.sgaws.wsvalidacion.soap.types.SgawsValidarDocente")
    @WebMethod(operationName = "sgaws_validar_docente", action = "sgaws_validar_docente")
    @ResponseWrapper(localName = "sgaws_validar_docenteResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsvalidacion/soap/types", className = "ec.edu.unl.ws.sgaws.wsvalidacion.soap.types.SgawsValidarDocenteResponse")
    public java.lang.String sgawsValidarDocente(
        @WebParam(name = "cedula", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsvalidacion/soap/types")
        java.lang.String cedula,
        @WebParam(name = "clave", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsvalidacion/soap/types")
        java.lang.String clave
    );

    /**
     * Metodo de comprobacion para servicios
     * 	
     */
    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsvalidacion/soap/types")
    @RequestWrapper(localName = "suma", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsvalidacion/soap/types", className = "ec.edu.unl.ws.sgaws.wsvalidacion.soap.types.Suma")
    @WebMethod(action = "suma")
    @ResponseWrapper(localName = "sumaResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsvalidacion/soap/types", className = "ec.edu.unl.ws.sgaws.wsvalidacion.soap.types.SumaResponse")
    public java.lang.String suma(
        @WebParam(name = "a", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsvalidacion/soap/types")
        java.lang.String a,
        @WebParam(name = "b", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsvalidacion/soap/types")
        java.lang.String b
    );

    /**
     * Este metodo recibe como parametros de entrada la cedula y la clave del estudiante.
     * 	Retorna true o false dependiendo de los si la informacion enviada pertenece a un estudiante.
     * 	
     */
    @WebResult(name = "result", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsvalidacion/soap/types")
    @RequestWrapper(localName = "sgaws_validar_estudiante", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsvalidacion/soap/types", className = "ec.edu.unl.ws.sgaws.wsvalidacion.soap.types.SgawsValidarEstudiante")
    @WebMethod(operationName = "sgaws_validar_estudiante", action = "sgaws_validar_estudiante")
    @ResponseWrapper(localName = "sgaws_validar_estudianteResponse", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsvalidacion/soap/types", className = "ec.edu.unl.ws.sgaws.wsvalidacion.soap.types.SgawsValidarEstudianteResponse")
    public java.lang.String sgawsValidarEstudiante(
        @WebParam(name = "cedula", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsvalidacion/soap/types")
        java.lang.String cedula,
        @WebParam(name = "clave", targetNamespace = "http://ws.unl.edu.ec/sgaws/wsvalidacion/soap/types")
        java.lang.String clave
    );
}
